# julia


<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

------------------------------------------------------------------------

<a
href="https://github.com/eandreas/fractalart/blob/main/fractalart/fractal.py#L200"
target="_blank" style="float:right; font-size:smaller">source</a>

### julia_step

>  julia_step (zr, zi, cr, ci)

------------------------------------------------------------------------

<a
href="https://github.com/eandreas/fractalart/blob/main/fractalart/fractal.py#L120"
target="_blank" style="float:right; font-size:smaller">source</a>

### smooth_coloring

>  smooth_coloring (zr, zi, iteration)

``` python
class Julia(Fractal):
    def __init__(
        self,
        x_min: float = None,
        x_max: float =  None,
        y_min: float = None,
        y_max: float =  None,
        cr: float = -0.7,
        ci: float = 0.27015,
        width: int = 600,
        height: int = 600,
        max_iter: int = 200,
    ):
        if None in (x_min, x_max, y_min, y_max):
            x_min, x_max, y_min, y_max = -1.5, 1.5, -1.5, 1.5
        self._x_min, self._x_max = x_min, x_max
        self._y_min, self._y_max = y_min, y_max
        self.resolution = width, height
        self.max_iter = max_iter
        self._cr = cr
        self._ci = ci
        
    def compute(self) -> np.ndarray:
        return _compute_julia(self._x_min, self._x_max, self._y_min, self._y_max, self._cr, self._ci, 
                                self.resolution, self._max_iter, julia_step)
```

``` python
j = Julia()
j.render()
j.equalize_histogram()
j.plot()
```

    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    NameError: name 'r4' is not defined
    During: Pass nopython_type_inference
    [0;31m---------------------------------------------------------------------------[0m
    [0;31mTypingError[0m                               Traceback (most recent call last)
    Cell [0;32mIn[8], line 2[0m
    [1;32m      1[0m j [38;5;241m=[39m Julia()
    [0;32m----> 2[0m [43mj[49m[38;5;241;43m.[39;49m[43mrender[49m[43m([49m[43m)[49m
    [1;32m      3[0m j[38;5;241m.[39mequalize_histogram()
    [1;32m      4[0m j[38;5;241m.[39mplot()

    File [0;32m~/projects/dev/fractalart/fractalart/core.py:49[0m, in [0;36mImage.render[0;34m(self)[0m
    [1;32m     47[0m [38;5;250m[39m[38;5;124;03m"""Render the image using subclass-defined logic."""[39;00m
    [1;32m     48[0m before [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_image[38;5;241m.[39mcopy()
    [0;32m---> 49[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_render[49m[43m([49m[43m)[49m
    [1;32m     50[0m [38;5;28;01mif[39;00m np[38;5;241m.[39marray_equal(before, [38;5;28mself[39m[38;5;241m.[39m_image):
    [1;32m     51[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mSubclasses must modify self._image during rendering.[39m[38;5;124m"[39m)

    File [0;32m~/projects/dev/fractalart/fractalart/fractal/abstract_fractal.py:85[0m, in [0;36mFractal._render[0;34m(self)[0m
    [1;32m     83[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_render[39m([38;5;28mself[39m):
    [1;32m     84[0m [38;5;250m    [39m[38;5;124;03m"""Generate and store the fractal image using the subclass-defined `compute` method."""[39;00m
    [0;32m---> 85[0m     [38;5;28mself[39m[38;5;241m.[39m_image [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcompute[49m[43m([49m[43m)[49m

    Cell [0;32mIn[7], line 24[0m, in [0;36mJulia.compute[0;34m(self)[0m
    [1;32m     23[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mcompute[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m np[38;5;241m.[39mndarray:
    [0;32m---> 24[0m     [38;5;28;01mreturn[39;00m [43m_compute_julia[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_x_min[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_x_max[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_y_min[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_y_max[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_cr[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_ci[49m[43m,[49m[43m [49m
    [1;32m     25[0m [43m                            [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mresolution[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_max_iter[49m[43m,[49m[43m [49m[43mjulia_step[49m[43m)[49m

    File [0;32m~/miniconda3/envs/art/lib/python3.11/site-packages/numba/core/dispatcher.py:424[0m, in [0;36m_DispatcherBase._compile_for_args[0;34m(self, *args, **kws)[0m
    [1;32m    420[0m         msg [38;5;241m=[39m ([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mstr[39m(e)[38;5;241m.[39mrstrip()[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124mThis error may have been caused [39m[38;5;124m"[39m
    [1;32m    421[0m                [38;5;124mf[39m[38;5;124m"[39m[38;5;124mby the following argument(s):[39m[38;5;130;01m\n[39;00m[38;5;132;01m{[39;00margs_str[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
    [1;32m    422[0m         e[38;5;241m.[39mpatch_message(msg)
    [0;32m--> 424[0m     [43merror_rewrite[49m[43m([49m[43me[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mtyping[39;49m[38;5;124;43m'[39;49m[43m)[49m
    [1;32m    425[0m [38;5;28;01mexcept[39;00m errors[38;5;241m.[39mUnsupportedError [38;5;28;01mas[39;00m e:
    [1;32m    426[0m     [38;5;66;03m# Something unsupported is present in the user code, add help info[39;00m
    [1;32m    427[0m     error_rewrite(e, [38;5;124m'[39m[38;5;124munsupported_error[39m[38;5;124m'[39m)

    File [0;32m~/miniconda3/envs/art/lib/python3.11/site-packages/numba/core/dispatcher.py:365[0m, in [0;36m_DispatcherBase._compile_for_args.<locals>.error_rewrite[0;34m(e, issue_type)[0m
    [1;32m    363[0m     [38;5;28;01mraise[39;00m e
    [1;32m    364[0m [38;5;28;01melse[39;00m:
    [0;32m--> 365[0m     [38;5;28;01mraise[39;00m e[38;5;241m.[39mwith_traceback([38;5;28;01mNone[39;00m)

    [0;31mTypingError[0m: Failed in nopython mode pipeline (step: nopython frontend)
    NameError: name 'r4' is not defined
    During: Pass nopython_type_inference
